services:
  # Backend Service
  - type: web
    name: shakira-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://gabriel:gabriel@bddshakira.l08bhec.mongodb.net/Shakira8Noviembre
      - key: JWT_SECRET
        generateValue: true
      - key: DEFAULT_PASSWORD
        value: FTT2025

  # Frontend Service  
  - type: web
    name: shakira-frontend
    env: static
    region: oregon  
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: frontend
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: shakira-backend
          property: url
        sync: false
