services:
  # Backend Service
  - type: web
    name: shakira-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://gabriel:gabriel@bddshakira.l08bhec.mongodb.net/Shakira8Noviembre
      - key: JWT_SECRET
        generateValue: true
      - key: DEFAULT_PASSWORD
        value: FTT2025
      - key: CORS_ORIGIN
        value: https://feelthecanjefttweb.onrender.com

  # Frontend Service  
  - type: web
    name: shakira-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: frontend
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /api/*
        destination: https://feelthecanjeftt.onrender.com/api/:splat
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://feelthecanjeftt.onrender.com
